# Always publish the latest CV build from the applications repo (Overleaf-synced).
cp ../arpitg_applications/cv/cv.pdf pdfs/cv.pdf
bundle exec jekyll build
# Normalize perms locally so Apache can read them once rsynced.
# (Restrictive local modes otherwise carry over and Apache returns 403; macOS
# ships BSD rsync 2.6.9, which lacks the --chmod=D/F prefixes, so we chmod here.)
find _site -type d -exec chmod 755 {} +
find _site -type f -exec chmod 644 {} +
rsync -a _site/ arpitgupta@linux.engr.ucsb.edu:~/public_html/

# blogs/ and blog/ are fully generated by Jekyll, so mirror them exactly with a
# scoped --delete. This purges posts that were removed or held out of the build
# (a plain `rsync -a` never deletes, so stale drafts would linger on the server).
# Scoped to these two dirs so non-repo content (book, course sites) is untouched.
for d in blogs blog; do
  [ -d "_site/$d" ] && rsync -a --delete "_site/$d/" "arpitgupta@linux.engr.ucsb.edu:~/public_html/$d/"
done
